# Cheatsheet Configuration Example
# This file demonstrates the available fields for cheat sheet entries
# This file also contains examples of invocation of the cheatsheet app itself

[[entry]]
title = "cs"
command = "cheatsheet"
description = "Shortcut for cheatsheet command"

[[entry]]
title = "cs list"
command = "cheatsheet list"
description = "List all available cheat sheet entries"

[[entry]]
title = "cs verbose"
command = "cheatsheet -vvv <other>"
description = "Enables verbose output for debugging purposes"
